//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public departamento()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int idDepartamento { get; set; }
        public string nombreDepto { get; set; }
        public Nullable<int> cantEmpleados { get; set; }
        public Nullable<int> codTels { get; set; }
    
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual telefono telefono { get; set; }
    }
}
