//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefono
    {
        public telefono()
        {
            this.departamento = new HashSet<departamento>();
        }
    
        public int codTels { get; set; }
        public string telefono1 { get; set; }
        public string telDescrip { get; set; }
    
        public virtual ICollection<departamento> departamento { get; set; }
    }
}
